import './globals.css'
import type { Metadata } from 'next'

// components
import Provider from '../components/Provider/Provider'

export const metadata: Metadata = {
  title: 'NextAuth.js',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <Provider>
        <body suppressHydrationWarning={true}>{children}</body>
      </Provider>
    </html>
  )
}
